on:
    pull_request:
      branches:
        - main

jobs:
    quick-scan:
      runs-on: ubuntu-latest
      env:
        AUDIT_AGENT_TOKEN: ${{ secrets.AUDIT_AGENT_TOKEN }}
      steps:
        - uses: actions/checkout@v4
        - name: Quick Scan
          run: |
            curl -X POST \-H "Content-Type: application/json" \-H "X-Api-Key: $AUDIT_AGENT_TOKEN" \-d '{
                "repositoryURL": "${{ github.event.repository.html_url }}",
                "branchName": "${{ github.event.pull_request.head.ref }}",
                "issueNumber": ${{ github.event.number }},
                "commitHash": "${{ github.event.pull_request.head.sha }}",
                "contractFiles": ["src/Counter.sol"]
              }' \https://47bf-2405-201-2017-c802-a16e-c245-bd3c-17f2.ngrok-free.app/api/v1/scanner/quick-scan/launch
